#include "ui_lang.h"

// =====================================================
//  Tables de traduction
// =====================================================

// ----- FRANCAIS -----
static const LangStrings lang_fr = {
    .lang_name      = "Francais",
    .days           = {"Dimanche","Lundi","Mardi","Mercredi","Jeudi","Vendredi","Samedi"},
    .months         = {"janvier","fevrier","mars","avril","mai","juin",
                       "juillet","aout","septembre","octobre","novembre","decembre"},
    .radio_title    = "RADIO WEB",
    .mp3_select_file= "-- Selectionnez un fichier --",
    .mp3_no_file    = "Aucun MP3 trouve",
    .mp3_create_folder = "Creez le dossier /mp3",
    .mp3_err_sd     = "! Erreur Carte SD",
    .config_title      = "CONFIGURATION",
    .config_brightness = "Luminosite",
    .config_volume     = "Volume",
    .config_btn_wifi   = "WiFi",
    .config_btn_alarm  = "Alarme",
    .config_btn_leds   = "LEDs",
    .config_btn_eq     = "EQ",
    .config_btn_themes = "Themes",
    .config_btn_tz     = "Fuseau",
    .config_btn_lang   = "Langue",
    .config_btn_info   = "Info",
    .wifi_title     = "GESTION WIFI",
    .wifi_back      = "Retour",
    .wifi_scan      = "Scanner",
    .wifi_saved     = "RESEAUX ENREGISTRES",
    .wifi_connected = "Connecte",
    .wifi_lost      = "WiFi perdu...",
    .wifi_scanning  = "Scan en cours...",
    .wifi_available = "RESEAUX DISPONIBLES",
    .wifi_no_saved  = "Aucun reseau enregistre.\nUtilisez Scanner pour ajouter.",
    .wifi_no_network= "Aucun reseau trouve.",
    .wifi_pwd_placeholder = "Mot de passe WiFi...",
    .alarm_title    = "REGLAGE ALARME",
    .alarm_mode     = "Mode",
    .alarm_validate = "Valider",
    .led_title      = "REGLAGE LED",
    .led_fixed      = "Fixe",
    .led_rainbow    = "Arc-en-ciel",
    .led_wave       = "Vague",
    .led_pulse      = "Pulse",
    .led_validate   = "Valider",
    .eq_title       = "EQUALIZER",
    .eq_bass        = "Basses",
    .eq_mid         = "Mediums",
    .eq_treble      = "Aigus",
    .eq_validate    = "OK",
    .theme_title    = "THEMES",
    .theme_validate = "Valider",
    .tz_title       = "FUSEAU HORAIRE",
    .tz_validate    = "Valider",
    .lang_title     = "LANGUE",
    .lang_validate  = "Valider",
    .info_title     = "SYSTEME INFO",
    .info_signal    = "Signal",
    .info_sd        = "Espace SD",
    .info_temp      = "Temp CPU",
    .led_brightness = "Luminosite LEDs",
    .led_color_preview = "Couleur",
    .err_no_wifi    = "Pas de WiFi",
    .err_no_sd      = "Carte SD absente",
    .err_no_rtc     = "RTC introuvable",
    .err_stream     = "Erreur flux",
};

// ----- ENGLISH -----
static const LangStrings lang_en = {
    .lang_name      = "English",
    .days           = {"Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"},
    .months         = {"January","February","March","April","May","June",
                       "July","August","September","October","November","December"},
    .radio_title    = "WEB RADIO",
    .mp3_select_file= "-- Select a file --",
    .mp3_no_file    = "No MP3 found",
    .mp3_create_folder = "Create the /mp3 folder",
    .mp3_err_sd     = "! SD Card Error",
    .config_title      = "SETTINGS",
    .config_brightness = "Brightness",
    .config_volume     = "Volume",
    .config_btn_wifi   = "WiFi",
    .config_btn_alarm  = "Alarm",
    .config_btn_leds   = "LEDs",
    .config_btn_eq     = "EQ",
    .config_btn_themes = "Themes",
    .config_btn_tz     = "Timezone",
    .config_btn_lang   = "Language",
    .config_btn_info   = "Info",
    .wifi_title     = "WIFI MANAGER",
    .wifi_back      = "Back",
    .wifi_scan      = "Scan",
    .wifi_saved     = "SAVED NETWORKS",
    .wifi_connected = "Connected",
    .wifi_lost      = "WiFi lost...",
    .wifi_scanning  = "Scanning...",
    .wifi_available = "AVAILABLE NETWORKS",
    .wifi_no_saved  = "No saved network.\nUse Scan to add one.",
    .wifi_no_network= "No network found.",
    .wifi_pwd_placeholder = "WiFi password...",
    .alarm_title    = "ALARM SETTINGS",
    .alarm_mode     = "Mode",
    .alarm_validate = "Confirm",
    .led_title      = "LED SETTINGS",
    .led_fixed      = "Fixed",
    .led_rainbow    = "Rainbow",
    .led_wave       = "Wave",
    .led_pulse      = "Pulse",
    .led_validate   = "Confirm",
    .eq_title       = "EQUALIZER",
    .eq_bass        = "Bass",
    .eq_mid         = "Mid",
    .eq_treble      = "Treble",
    .eq_validate    = "OK",
    .theme_title    = "THEMES",
    .theme_validate = "Confirm",
    .tz_title       = "TIME ZONE",
    .tz_validate    = "Confirm",
    .lang_title     = "LANGUAGE",
    .lang_validate  = "Confirm",
    .info_title     = "SYSTEM INFO",
    .info_signal    = "Signal",
    .info_sd        = "SD Space",
    .info_temp      = "CPU Temp",
    .led_brightness = "LED Brightness",
    .led_color_preview = "Color",
    .err_no_wifi    = "No WiFi",
    .err_no_sd      = "SD card missing",
    .err_no_rtc     = "RTC not found",
    .err_stream     = "Stream error",
};

// ----- ESPAGNOL -----
static const LangStrings lang_es = {
    .lang_name      = "Espanol",
    .days           = {"Domingo","Lunes","Martes","Miercoles","Jueves","Viernes","Sabado"},
    .months         = {"enero","febrero","marzo","abril","mayo","junio",
                       "julio","agosto","septiembre","octubre","noviembre","diciembre"},
    .radio_title    = "RADIO WEB",
    .mp3_select_file= "-- Seleccione un archivo --",
    .mp3_no_file    = "No se encontro MP3",
    .mp3_create_folder = "Cree la carpeta /mp3",
    .mp3_err_sd     = "! Error tarjeta SD",
    .config_title      = "CONFIGURACION",
    .config_brightness = "Brillo",
    .config_volume     = "Volumen",
    .config_btn_wifi   = "WiFi",
    .config_btn_alarm  = "Alarma",
    .config_btn_leds   = "LEDs",
    .config_btn_eq     = "EQ",
    .config_btn_themes = "Temas",
    .config_btn_tz     = "Zona",
    .config_btn_lang   = "Idioma",
    .config_btn_info   = "Info",
    .wifi_title     = "GESTION WIFI",
    .wifi_back      = "Volver",
    .wifi_scan      = "Escanear",
    .wifi_saved     = "REDES GUARDADAS",
    .wifi_connected = "Conectado",
    .wifi_lost      = "WiFi perdido...",
    .wifi_scanning  = "Escaneando...",
    .wifi_available = "REDES DISPONIBLES",
    .wifi_no_saved  = "Sin redes guardadas.\nUse Escanear para anadir.",
    .wifi_no_network= "No se encontro red.",
    .wifi_pwd_placeholder = "Contrasena WiFi...",
    .alarm_title    = "AJUSTE ALARMA",
    .alarm_mode     = "Modo",
    .alarm_validate = "Confirmar",
    .led_title      = "AJUSTE LED",
    .led_fixed      = "Fijo",
    .led_rainbow    = "Arcoiris",
    .led_wave       = "Ola",
    .led_pulse      = "Pulso",
    .led_validate   = "Confirmar",
    .eq_title       = "ECUALIZADOR",
    .eq_bass        = "Graves",
    .eq_mid         = "Medios",
    .eq_treble      = "Agudos",
    .eq_validate    = "OK",
    .theme_title    = "TEMAS",
    .theme_validate = "Confirmar",
    .tz_title       = "ZONA HORARIA",
    .tz_validate    = "Confirmar",
    .lang_title     = "IDIOMA",
    .lang_validate  = "Confirmar",
    .info_title     = "INFO SISTEMA",
    .info_signal    = "Senal",
    .info_sd        = "Espacio SD",
    .info_temp      = "Temp CPU",
    .led_brightness = "Brillo LEDs",
    .led_color_preview = "Color",
    .err_no_wifi    = "Sin WiFi",
    .err_no_sd      = "SD ausente",
    .err_no_rtc     = "RTC no encontrado",
    .err_stream     = "Error de flujo",
};

// ----- ITALIEN -----
static const LangStrings lang_it = {
    .lang_name      = "Italiano",
    .days           = {"Domenica","Lunedi","Martedi","Mercoledi","Giovedi","Venerdi","Sabato"},
    .months         = {"gennaio","febbraio","marzo","aprile","maggio","giugno",
                       "luglio","agosto","settembre","ottobre","novembre","dicembre"},
    .radio_title    = "RADIO WEB",
    .mp3_select_file= "-- Seleziona un file --",
    .mp3_no_file    = "Nessun MP3 trovato",
    .mp3_create_folder = "Crea la cartella /mp3",
    .mp3_err_sd     = "! Errore scheda SD",
    .config_title      = "CONFIGURAZIONE",
    .config_brightness = "Luminosita",
    .config_volume     = "Volume",
    .config_btn_wifi   = "WiFi",
    .config_btn_alarm  = "Sveglia",
    .config_btn_leds   = "LEDs",
    .config_btn_eq     = "EQ",
    .config_btn_themes = "Temi",
    .config_btn_tz     = "Fuso",
    .config_btn_lang   = "Lingua",
    .config_btn_info   = "Info",
    .wifi_title     = "GESTIONE WIFI",
    .wifi_back      = "Indietro",
    .wifi_scan      = "Scansiona",
    .wifi_saved     = "RETI SALVATE",
    .wifi_connected = "Connesso",
    .wifi_lost      = "WiFi perso...",
    .wifi_scanning  = "Scansione in corso...",
    .wifi_available = "RETI DISPONIBILI",
    .wifi_no_saved  = "Nessuna rete salvata.\nUsa Scansiona per aggiungere.",
    .wifi_no_network= "Nessuna rete trovata.",
    .wifi_pwd_placeholder = "Password WiFi...",
    .alarm_title    = "IMPOSTAZIONI SVEGLIA",
    .alarm_mode     = "Modalita",
    .alarm_validate = "Conferma",
    .led_title      = "IMPOSTAZIONI LED",
    .led_fixed      = "Fisso",
    .led_rainbow    = "Arcobaleno",
    .led_wave       = "Onda",
    .led_pulse      = "Impulso",
    .led_validate   = "Conferma",
    .eq_title       = "EQUALIZZATORE",
    .eq_bass        = "Bassi",
    .eq_mid         = "Medi",
    .eq_treble      = "Alti",
    .eq_validate    = "OK",
    .theme_title    = "TEMI",
    .theme_validate = "Conferma",
    .tz_title       = "FUSO ORARIO",
    .tz_validate    = "Conferma",
    .lang_title     = "LINGUA",
    .lang_validate  = "Conferma",
    .info_title     = "INFO DI SISTEMA",
    .info_signal    = "Segnale",
    .info_sd        = "Spazio SD",
    .info_temp      = "Temp CPU",
    .led_brightness    = "Luminosita LED", 
    .led_color_preview = "Colore",
    .err_no_wifi    = "Nessun WiFi",
    .err_no_sd      = "SD assente",
    .err_no_rtc     = "RTC non trovato",
    .err_stream     = "Errore di streaming",
};

// ----- ALLEMAND -----
static const LangStrings lang_de = {
    .lang_name      = "Deutsch",
    .days           = {"Sonntag","Montag","Dienstag","Mittwoch","Donnerstag","Freitag","Samstag"},
    .months         = {"Januar","Februar","Marz","April","Mai","Juni",
                       "Juli","August","September","Oktober","November","Dezember"},
    .radio_title    = "WEB RADIO",
    .mp3_select_file= "-- Datei auswahlen --",
    .mp3_no_file    = "Keine MP3 gefunden",
    .mp3_create_folder = "Ordner /mp3 erstellen",
    .mp3_err_sd     = "! SD-Kartenfehler",
    .config_title      = "EINSTELLUNGEN",
    .config_brightness = "Helligkeit",
    .config_volume     = "Lautstarke",
    .config_btn_wifi   = "WiFi",
    .config_btn_alarm  = "Wecker",
    .config_btn_leds   = "LEDs",
    .config_btn_eq     = "EQ",
    .config_btn_themes = "Designs",
    .config_btn_tz     = "Zeitzone",
    .config_btn_lang   = "Sprache",
    .config_btn_info   = "Info",
    .wifi_title     = "WLAN-VERWALTUNG",
    .wifi_back      = "Zuruck",
    .wifi_scan      = "Suchen",
    .wifi_saved     = "GESP. NETZWERKE",
    .wifi_connected = "Verbunden",
    .wifi_lost      = "WLAN verloren...",
    .wifi_scanning  = "Suchen...",
    .wifi_available = "VERFUGBARE NETZWERKE",
    .wifi_no_saved  = "Keine gesp. Netzwerke.\nZum Hinzufugen suchen.",
    .wifi_no_network= "Kein Netzwerk gefunden.",
    .wifi_pwd_placeholder = "WLAN-Passwort...",
    .alarm_title    = "WECKZEIT EINSTELLEN",
    .alarm_mode     = "Modus",
    .alarm_validate = "Bestatigen",
    .led_title      = "LED EINSTELLUNGEN",
    .led_fixed      = "Statisch",
    .led_rainbow    = "Regenbogen",
    .led_wave       = "Welle",
    .led_pulse      = "Puls",
    .led_validate   = "Bestatigen",
    .eq_title       = "EQUALIZER",
    .eq_bass        = "Bass",
    .eq_mid         = "Mitten",
    .eq_treble      = "Hohen",
    .eq_validate    = "OK",
    .theme_title    = "DESIGNS",
    .theme_validate = "Bestatigen",
    .tz_title       = "ZEITZONE",
    .tz_validate    = "Bestatigen",
    .lang_title     = "SPRACHE",
    .lang_validate  = "Bestatigen",
    .info_title     = "SYSTEM-INFO",
    .info_signal    = "Signal",
    .info_sd        = "SD-Speicher",
    .info_temp      = "CPU-Temp",
    .led_brightness    = "LED-Helligkeit",
    .led_color_preview = "Farbe",
    .err_no_wifi    = "Kein WLAN",
    .err_no_sd      = "Keine SD",
    .err_no_rtc     = "RTC nicht gefunden",
    .err_stream     = "Stream-Fehler",
};

// ----- PORTUGAIS -----
static const LangStrings lang_pt = {
    .lang_name      = "Portugais",
    .days           = {"Domingo","Segunda","Terça","Quarta","Quinta","Sexta","Sabado"},
    .months         = {"janeiro","fevereiro","março","abril","maio","junho",
                       "julho","agosto","setembro","outubro","novembro","dezembro"},
    .radio_title    = "RADIO WEB",
    .mp3_select_file= "-- Selecione um arquivo --",
    .mp3_no_file    = "Nenhum MP3 encontrado",
    .mp3_create_folder = "Crie a pasta /mp3",
    .mp3_err_sd     = "! Erro Cartao SD",
    .config_title      = "CONFIGURACAO",
    .config_brightness = "Brilho",
    .config_volume     = "Volume",
    .config_btn_wifi   = "WiFi",
    .config_btn_alarm  = "Alarme",
    .config_btn_leds   = "LEDs",
    .config_btn_eq     = "EQ",
    .config_btn_themes = "Temas",
    .config_btn_tz     = "Fuso",
    .config_btn_lang   = "Idioma",
    .config_btn_info   = "Info",
    .wifi_title     = "GESTAO WIFI",
    .wifi_back      = "Voltar",
    .wifi_scan      = "Escanear",
    .wifi_saved     = "REDES SALVAS",
    .wifi_connected = "Conectado",
    .wifi_lost      = "WiFi perdido...",
    .wifi_scanning  = "Escaneando...",
    .wifi_available = "REDES DISPONIVEIS",
    .wifi_no_saved  = "Nenhuma rede salva.\nUse Escanear para adicionar.",
    .wifi_no_network= "Nenhuma rede encontrada.",
    .wifi_pwd_placeholder = "Senha WiFi...",
    .alarm_title    = "AJUSTE ALARME",
    .alarm_mode     = "Modo",
    .alarm_validate = "Confirmar",
    .led_title      = "AJUSTE LED",
    .led_fixed      = "Fixo",
    .led_rainbow    = "Arco-iris",
    .led_wave       = "Onda",
    .led_pulse      = "Pulso",
    .led_validate   = "Confirmar",
    .eq_title       = "EQUALIZADOR",
    .eq_bass        = "Graves",
    .eq_mid         = "Medios",
    .eq_treble      = "Agudos",
    .eq_validate    = "OK",
    .theme_title    = "TEMAS",
    .theme_validate = "Confirmar",
    .tz_title       = "FUSO HORARIO",
    .tz_validate    = "Confirmar",
    .lang_title     = "IDIOMA",
    .lang_validate  = "Confirmar",
    .info_title     = "INFO SISTEMA",
    .info_signal    = "Sinal",
    .info_sd        = "Espaco SD",
    .info_temp      = "Temp CPU",
    .led_brightness = "Brilho LEDs",
    .led_color_preview = "Cor",
    .err_no_wifi    = "Sem WiFi",
    .err_no_sd      = "Cartao SD ausente",
    .err_no_rtc     = "RTC nao encontrado",
    .err_stream     = "Erro de stream",
};

// =====================================================
//  Table de dispatch
// =====================================================
static const LangStrings* lang_table[LANG_COUNT] = {
    &lang_fr,   // LANG_FR = 0
    &lang_en,   // LANG_EN = 1
    &lang_es,   // LANG_ES = 2
    &lang_it,   // LANG_IT = 3
    &lang_de,   // LANG_DE = 4
    &lang_pt,   // LANG_PT = 5
};

const char* lang_names[LANG_COUNT] = {
    "Francais",
    "English",
    "Espanol",
    "Italien",
    "Allemand",
    "Portugais",
};

// Pointeur global utilise partout dans l'UI
const LangStrings* lang = &lang_fr;

void apply_language(int lang_id) {
    if (lang_id < 0 || lang_id >= LANG_COUNT) lang_id = LANG_FR;
    lang = lang_table[lang_id];
    Serial.printf("[LANG] Langue appliquee : %s\n", lang->lang_name);
}



